require 'cgi'
require 'json'
require 'base64'
require 'singleton'
require 'bigdecimal'
require 'forwardable'
require 'sinatra/base'

require_relative 'restful_objects/version'
require_relative 'restful_objects/router'
require_relative 'restful_objects/domain_model/domain_model'
